# Generated by Django 6.0.4 on 2026-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('anchor_url', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=10)),
                ('movie_title', models.CharField(max_length=20)),
                ('lower_rating', models.CharField(max_length=5)),
                ('upper_rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_alt', models.CharField(max_length=100)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
