# Generated by Django 6.0.4 on 2026-04-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_src', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AddField(
            model_name='slider',
            name='anchor_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='lower_rating',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='slider',
            name='movie_genre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='slider',
            name='movie_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='upper_rating',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='movietheater',
            name='movie_genre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movietheater',
            name='movie_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movietv',
            name='movie_genre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movietv',
            name='movie_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_src',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='TrailerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.trailer')),
            ],
        ),
    ]
